sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t7S6ZDNmBZtBjVvo2yE
    access-key-secret: 1mubSwWUUpTnIqPc9YW6C8rer7MWNF
    bucket-name: kuikuiwww
  redis:
    host: localhost
    port: 6379
    database: 10
    password: ""
  wechat:
    appid: wx7c49bba0c271f7c6
    secret: 8e55fe81ecd06b73ed90c8613dc9db70
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
